{% set name = "odc-algo" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: b48a2cd98a5cb0ac6d4f2cd81f69c9fca876a53e84ee99b9178efb36a3d271b2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - affine
    - datacube >=1.8.5
    - dask
    - dask-image
    - numexpr
    - numpy
    - rasterio
    - scikit-image
    - toolz
    - xarray

test:
  imports:
    - odc.algo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-tools/tree/develop/libs/algo
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://github.com/opendatacube/odc-tools/tree/develop/libs/algo
  dev_url: https://github.com/opendatacube/odc-tools/tree/develop/libs/algo
  summary: Miscellaneous Algorithmic helper methods (open datacube)

  description: |
    Various operations and algroithms that might be useful when working with
    geospatial rasters.


extra:
  recipe-maintainers:
    - kirill888
